### ISSUE TITLE
When a diff results in a section update + row move + section update, the data is incorrect and causes a crash.

### ISSUE THREAD

**Issue by SkylerSeamans** [ra1028/DifferenceKit#106]
## Checklist
- [X] This is not a Apple's bug.  
- [X Reviewed the [README](https://github.com/ra1028/DifferenceKit/blob/master/README.md) and [documents](https://ra1028.github.io/DifferenceKit).  
- [X] Searched [existing issues](https://github.com/ra1028/DifferenceKit/issues) for ensure not duplicated.  

## Expected Behavior
When a diff results in a section update + row move + section update, the data returned in the closure after each change should match the changeset.

## Current Behavior
When a diff results in a section update + move move + section update, the data returned in the closure after the row move change does not reflect the move and causes a UITableView crash when applied.

## Steps to Reproduce
I've provided a Playground to reproduce this issue, but here is a description of the steps I took:

1. Create a section model such that isContentEqual returns false if the count of items changes.
2. Create a simple row model 
3. Create a dataset so one row moves from one section to the other.
4. This dataset should result in a changeset that is a section update/row move/section update when a row is moved.

## Reproducible Demo Project
https://gist.github.com/SkylerSeamans/647b772a83be036f88946cee318420d5

## Environments
- Library version:
1.1.5
- Swift version:
5
- iOS version:
13
- Xcode version:
11.5
- Devices/Simulators:
Both
- CocoaPods/Carthage version:
1.9.1

**Comment by ra1028** [comment]
@SkylerSeamans 
Sorry for my late reply! and thanks for your reporting.
Perhaps that's a failure in the logic in the reproduction of section. In other words, you need to implement `init<C: Swift.Collection>(source: Self, elements: C) where C.Element == Collection.Element` correctly.
Please try modifying the sample code you provided as follows. It probably works fine.

```swift
    /// Used for DifferentiableSection
    public required convenience init<C: Swift.Collection>(source: SectionViewModel, elements: C) where C.Element == CellViewModel {
        self.init(
            title: SectionViewModel.title(
                status: source.status, count: elements.count
            ),
            status: source.status,
            elements: Array(elements)
        )
    }

    convenience init(status: Status, elements: [CellViewModel]) {
        self.init(
            title: SectionViewModel.title(status: status, count: elements.count),
            status: status,
            elements: elements
        )
    }

    init(title: String, status: Status, elements: [CellViewModel]) {
        self.title = title
        self.status = status
        self.elements = elements
    }
```

**Comment by SkylerSeamans** [comment]
Confirmed that fixed my problem! Thanks for the assistance and for creating a great framework!
