### ISSUE TITLE
Invalid Update: invalid number of sections. crash

### ISSUE THREAD

**Issue by ARamy23** [ra1028/DifferenceKit#108]
## Checklist
- [x] Reviewed the [README](https://github.com/ra1028/DifferenceKit/blob/master/README.md) and [documents](https://ra1028.github.io/DifferenceKit).  
- [x] Searched [existing issues](https://github.com/ra1028/DifferenceKit/issues) for ensure not duplicated.  

## Expected Behavior

TableView to display some messages sectioned by date (Date is a string) and messages are Differentiable with ids to differ them

## Current Behavior

It crashes at UIKitExtensions.swift > _performBatchUpdates(_:) with the following exception

"Invalid update: invalid number of sections. The number of sections contained in the table view after the update (3) must be equal to the number of sections contained in the table view before the update (0), plus or minus the number of sections inserted or deleted (0 inserted, 0 deleted)."

## Detailed Description (Include Screenshots)

The Section is String which conforms to Differentiable

the Elements Models are like this
![image](https://user-images.githubusercontent.com/31904352/85923849-c351b480-b88e-11ea-91e8-dbcc776198ca.png)
![image](https://user-images.githubusercontent.com/31904352/85923883-fd22bb00-b88e-11ea-9121-0cb91b10e56e.png)

I get the messages from the ViewModel and map it to ArraySection<String, Message>
like this
![image](https://user-images.githubusercontent.com/31904352/85923965-905bf080-b88f-11ea-8f8a-12a6ab67be18.png)

then the reload is like this
![image](https://user-images.githubusercontent.com/31904352/85924026-cbf6ba80-b88f-11ea-9f83-8d626a0675af.png)

I've been following articles and the documentation and made sure I follow them strictly but It keeps giving me this error

am I missing something?

## Environment
- Library version: 1.1.5

- Swift version: 5.1

- iOS version: 13.5

- Xcode version: 11.5

- Devices/Simulators: Simulator iPhone 11

- CocoaPods/Carthage version: CocoaPods 1.9.1

**Comment by nonameplum** [comment]
@ARamy23 Please paste code using

    ```swift
    func yourCode() {}
    ```
instead of the screenshots.

You didn't provide all of the data to easily spot the issue
* Is `chatViewModel.messagesSubject.subscribe { ... }` called on the main thread?
* Could you try to remove inheritance of `NSObject` for the `Message` class?

**Comment by ARamy23** [comment]
@nonameplum thanks a lot for ur response, i was able to fix it after exactly copting and pasting the code in the example project and it worked, I wasn’t sure what did i do wrong but it worked fine and our customers are happy with the new fast chat experience, thanks a lot for maintaining this
