### ISSUE TITLE
[FEATURE] Allow for performing different animations for update cell

### ISSUE THREAD

**Issue by Sameesunkaria** [ra1028/DifferenceKit#11]
It would be awesome if we could perform different type of animations for update cells. (or maybe all the actions in batch updates)

This need arises as we would like to update the cells without any animations, but perform the delete/insert/move with animations.

**Comment by ra1028** [comment]
Thanks for the suggestion @Sameesunkaria 👍 

It's difficult to provide a completely generic interface for all applications.
DIfferenceKit has a clean separation between UI and diffing algorithm.
I recommend you to implement extensions that have various functions in your project.

BTW, If you are using CocoaPods, you can install only the core diffing algorithm without UI extensions.
See [installation](https://github.com/ra1028/DifferenceKit#installation).
