### ISSUE TITLE
Duplicate items with some edge cases in AppKitExtension

### ISSUE THREAD

**Issue by paxos** [ra1028/DifferenceKit#139]
In some edge cases, the AppKit extension (and possibly UIKit extension) will produce duplicate items:

https://user-images.githubusercontent.com/121539/153323882-db1cb3dc-8d8f-4dce-8ea3-4105b3a2e4fc.mov

Example:
```
StagedChangeset(source: ["1","3"], target: ["3","2","1"])
```

This will produce the following changeset:
```
▿ [
    Changeset(
        data: [
            3,
            2,
            1
        ],
        elementInserted: [
            [element: 1, section: 0]
        ],
        elementMoved: [
            (source: [element: 1, section: 0], target: [element: 0, section: 0])
        ]
    )
]
```

The current implementation, as found here: https://github.com/ra1028/DifferenceKit/blob/62745d7780deef4a023a792a1f8f763ec7bf9705/Sources/Extensions/AppKitExtension.swift#L50-L91

will execute the following actions:
```
removeRows [[element: 1, section: 0]]
InsertRows [[element: 1, section: 0]]
Move [element: 1, section: 0] [element: 0, section: 0]
viewFor:row 0 😂
```

(The code that produced those logs can be found here: https://github.com/paxos/DifferenceKit/pull/1)

The problem: AppKit will ask the datasource for the element at position 0, while it should ask for the element at position 1. It turns out that, if you add a new element and then move it (before calling `endUpdates()`), AppKit will request the element from the _new_ position.

### Possible solution
A possible solution could be to change the order of things, for example:

```
view.beginUpdates()
handleDeletes…
handleInserts…
view.endUpdates() <-- this will cause AppKit to reach out to the datasource with the correct index
view.beginUpdates()
handleMoves…
view.endUpdates
```

https://user-images.githubusercontent.com/121539/153324303-c2032ce6-87af-466b-a628-a25720cd6bfe.mov

## Checklist
- [x] This is not a Apple's bug.  
- [x] Reviewed the [README](https://github.com/ra1028/DifferenceKit/blob/master/README.md) and [documents](https://ra1028.github.io/DifferenceKit).  
- [X] Searched [existing issues](https://github.com/ra1028/DifferenceKit/issues) for ensure not duplicated.

**Comment by paxos** [comment]
I found another sequence that does not produce the correct results:

```
StagedChangeset(source: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], target: ["5", "1", "7", "4", "2", "10"])
```

If this gets applied via AppKit extension `tableView.reload`, the result are as follow:

Should be:  ["5", "1", "7", "4", "2", "10"]
But is:  ["5", "1", "2", "7", "4", "10"]

**Comment by paxos** [comment]
I dont think any of the unit tests will capture this, as none of them check what the actual state is that AppKit ends up in. Any advice how this could be fixed?

Unfortunately, this is a serious issue and produces wrong results in some scenarios.

**Comment by paxos** [comment]
I added some code that compares data vs AppKit state and demonstrates the mentioned error sequence:

https://github.com/paxos/DifferenceKit/pull/2

**Comment by martindufort** [comment]
Any resolution on this as I'm seeing the same issue in the Appkit extension.

**Comment by ra1028** [comment]
I actually am not quite familiar with AppKit and the AppKit extension was added by another developer in [this PR](https://github.com/ra1028/DifferenceKit/pull/29). So I won't give you any good resolution on the issue but if the proposed way works in any cases including edge cases and it's proved somehow, I would accept it to merge.

**Comment by paxos** [comment]
The only working solution in the whole internet that I could find that is working reliable for AppKit was written by @GilesHammond and a version of it can be found here: https://github.com/paxos/NSOutlineViewPatchTestSuite/pull/1

We added a test suite with randomized tests to verify this, and so far it has been working flawlessly.

**Comment by ra1028** [comment]
Interesting. It must be worth trying to incorporate into DifferenceKit if it really did pass 50k randomized test cases. Can you create a PR for it?

**Comment by tobiasjordan** [comment]
Can anyone run the 50k randomized test cases for my PR #144? Would be really great as I haven't found the time yet to implement some tests for my proposed solution.

**Comment by paxos** [comment]
@tobiasjordan I have updated the testsuite to use differencekit here: 
https://github.com/paxos/NSOutlineViewPatchTestSuite/tree/use-differencekit

Your fix is used starting in 6a31c8ab9dfa3f0d84e90653ba6906bd8345cc19 and so far it looks promising. 10K run successfully, 50K is still running.

**Comment by GilesHammond** [comment]
Sorry Patrick. 
I’ve been slack on sharing this as a package!
Would that be helpful in this case?

Giles

**Comment by paxos** [comment]
> Sorry Patrick. I’ve been slack on sharing this as a package! Would that be helpful in this case? Giles
> […](#)
> On 27 May 2022, at 19:28, Patrick Dinger ***@***.***> wrote: ﻿ I am not sure. The solution is based on native Swift CollectionDifference. I believe the steps returned by DifferenceKit are not 100% compatible with the Sequence that AppKit expects each step to get applied. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

no worries, i am good for now! thanks
