### ISSUE TITLE
Does it work seamlessly when using an UICollectionView with SwiftUI cells?

### ISSUE THREAD

**Issue by filipealva** [ra1028/DifferenceKit#149]
## Checklist
- [x] Reviewed the [README](https://github.com/ra1028/DifferenceKit/blob/master/README.md) and [documents](https://ra1028.github.io/DifferenceKit).  
- [x] Searched [existing issues](https://github.com/ra1028/DifferenceKit/issues) for ensure not duplicated.  

Hello,

I'm considering adopting DifferenceKit on a new project. One of the requirements is to use UICollectionViews with SwiftUI cells.

Does it work in this context? 

Thank you

**Comment by ra1028** [comment]
I've never tried so far but it should work as the cell content is not a matter for DifferenceKit.

**Comment by filipealva** [comment]
That makes sense. Thanks for answering.
