### ISSUE TITLE
Compare with Changeset?

### ISSUE THREAD

**Issue by osteslag** [ra1028/DifferenceKit#16]
Thanks for releasing DifferenceKit, it looks really cool.

I’m the author of [Changeset](https://github.com/osteslag/Changeset), another fairly popular lightweight diffing framework. When you have the time, maybe I can persuade you to include it in your [comparison](https://github.com/ra1028/DifferenceKit#comparison-with-other-frameworks)?

Thanks in advance.

**Comment by ra1028** [comment]
Hi @osteslag .

Of course I know your framework 👍 
That's cool, too.

I also know that Changeset adpts the Wagner-Fischer algorithm algorithm, but it doesn't perform fast.
It's adopted in Dwifft too.
The measured time will be as slow as Dwifft, is it still okay?

**Comment by osteslag** [comment]
Oh, right. That’s fine then. Feel free to close this issue.

**Comment by ra1028** [comment]
@osteslag 
Then, I will add a comparison with Changeset. If you feel disagreeable, please open the issue again and mention to me.

**Comment by ra1028** [comment]
@osteslag 
Sorry, I gave up since it takes more than 30 minutes to measuring 1000 deletions and 1000 insertions from 5000 element which is the minimum data size put on comparison.

**Comment by osteslag** [comment]
Interesting. Changeset is written for ease of use and simplicity. But this is a little surprising. Thanks for testing it, I appreciate your effort.

**Comment by ra1028** [comment]
I know Changeset is an excellent framework from a perspective other than performance.
Thanks for being interested in DifferenceKit 👍

**Comment by osteslag** [comment]
I will be using DifferenceKit in the future when I’m expecting a lot of data and/or need fast operation. Thanks.
