### ISSUE TITLE
`setData` closure gets called outside of `performBatchUpdates`

### ISSUE THREAD

**Issue by Usipov** [ra1028/DifferenceKit#17]
Hey! Thanks for an amazing tool
I tried it out in stress tests (will probably share the code later) and found unexpected crashes.
The issue was due to the [following code](https://github.com/ra1028/DifferenceKit/blob/master/Sources/UIExtensions/UIKitExtension.swift#L77)
![screen shot 2018-08-27 at 17 40 53](https://user-images.githubusercontent.com/1080247/44666251-a349d380-aa20-11e8-8956-c00b621bca07.png)

Here `setData` gets called not inside of `performBatchUpdates`.
But according to the [docs](https://developer.apple.com/documentation/uikit/uicollectionview/1618045-performbatchupdates), it should be done inside: 
```
To avoid problems, you should update your data model inside the updates block or ensure the layout is updated before you call performBatchUpdates(_:completion:).
```

**Comment by ra1028** [comment]
Hi @Usipov 
Thanks for the precious bug report.
I didn't know that its specification of UICollectionView.

I'll do that in the next release.
I'm waiting for you to share me your stress tests code 👍

**Comment by ra1028** [comment]
WIP https://github.com/ra1028/DifferenceKit/pull/18

**Comment by ra1028** [comment]
@Usipov 
Could you share me the codes of your tests?
