### ISSUE TITLE
Diff calculation sometimes misses `insert` operation

### ISSUE THREAD

**Issue by larryonoff** [ra1028/DifferenceKit#21]
Sometimes I have a crash when one item is deleted and another one is inserted in the same section. Their diff identifiers are not equal. It looks that issue occurs when a table view is updated the second time or later (not the first).

The data structure looks in the following way.
before = [s1 :[1, 2], s2: [3]]
current = [s1 :[1, 2], s2: [4]]

So library calculates only delete of `3` in the section `s2`, but not insert of `4`.

I don't have a good sample yet. But I'll do as soon as I catch it during debug.

**Comment by ra1028** [comment]
@larryonoff 
Update of UITable/CollectionView using StagedChangeset is applied gradually.
Since `performBatchUpdates` is called at each stage, you need to update the data source just before each.
Please make sure that you are updating the data-source in the `setData` closure.
```swift
let changeset =  StagedChangeset(source: source, target: target)
collectionView.reload(using: changeset, setData: {  data in
    dataSource.data = data
})
```
You can find example app at [here](https://github.com/ra1028/DifferenceKit/blob/master/Examples/Example-iOS/Sources/ShuffleEmoticonViewController.swift)

**Comment by larryonoff** [comment]
Thank you for the comment.

This's what I do
```
        let newDataSource = itemBuilder.items(from: newState)

        if dataSource.isEmpty {
            dataSource = newDataSource
            state = newState

            tableView?.reloadData()
        } else {
            let changeset = StagedChangeset(source: dataSource, target: newDataSource)

            tableView?.reload(
                using: changeset,
                with: .automatic,
                setData: { _ in
                    self.dataSource = newDataSource
                    self.state = newState
                })
        }
```

**Comment by larryonoff** [comment]
I've found that the main difference in my code is

```
                setData: { _ in
                    self.dataSource = newDataSource
                    self.state = newState
                })
```

**Comment by ra1028** [comment]
@larryonoff 
Please use the data passed as a parameter to the `setData` closure.
The closure called multiple times, and the changes are applied to each data in stages.
Did you see the [example app](https://github.com/ra1028/DifferenceKit/blob/master/Examples/Example-iOS/Sources/ShuffleEmoticonViewController.swift)?

The structure of `StagedChangeset` looks in the following.
```swift
let source = [
    ArraySection(model: "Section 1", elements: ["1", "2"]),
    ArraySection(model: "Section 2", elements: ["3"])
]

let target = [
    ArraySection(model: "Section 1", elements: ["1", "2"]),
    ArraySection(model: "Section 2", elements: ["4"])
]

let changeset = StagedChangeset(source: source, target: target)
print(changeset)

```
```swift
[
    Changeset(
        data: [
            ArraySection(
                model: Section 1,
                elements: ["1", "2"]
            ),
            ArraySection(model: Section 2, elements: [])
        ],
        elementDeleted: [
            [element: 0, section: 1]
        ]
    ),
    Changeset(
        data: [
            ArraySection(
                model: Section 1,
                elements: ["1", "2"]
            ),
            ArraySection(
                model: Section 2,
                elements: ["4"]
            )
        ],
        elementInserted: [
            [element: 0, section: 1]
        ]
    )
]
```

**Comment by larryonoff** [comment]
@ra1028 thanks for the help. I updated data in `setData`, but I missed info about `setData` parameter that have to be used.

**Comment by larryonoff** [comment]
@ra1028 I have the following proposal. Introduce callback, e.g. `completed` that notifies that reload operation is completed. The case that I see is when you calculate changes in background and send changeset in .main for reload.

**Comment by Sameesunkaria** [comment]
@ra1028 How about changing the note about using the argument in setData to a completely bold sentence? Also in the readme setData is misspelled as setDate

**Comment by Sameesunkaria** [comment]
@larryonoff there’s an issue about that. Refer to #7

**Comment by larryonoff** [comment]
@Sameesunkaria thanks! I think that proposed solution in #7 is workaround, but not solution.

**Comment by ra1028** [comment]
@larryonoff 
Please change your codes as follows.
```swift
setData: { data in
    self.dataSource = data
    self.state = newState
})
```

> I missed info about setData parameter that have to be used.

It's described in [readme](https://github.com/ra1028/DifferenceKit/blob/master/README.md#getting-started) and the [docs](https://ra1028.github.io/DifferenceKit/Extensions/UICollectionView.html#/s:So16UICollectionViewC13DifferenceKitE6reloadyAC15StagedChangesetVyxG5using_SbAC0G0VyxGcSg9interruptyxc7setDatats10CollectionRzlF)

> thanks! I think that proposed solution in #7 is workaround, but not solution.

Any idea?

@Sameesunkaria
Thanks!

> How about changing the note about using the argument in setData to a completely bold sentence? Also in the readme setData is misspelled as setDate

Feel free to pull request.

**Comment by larryonoff** [comment]
@ra1028 absolutely will do! But a bit later.

**Comment by larryonoff** [comment]
@Sameesunkaria This not problem for me. But this's not important for me at the moment. I just love this library and want to do it better.

**Comment by ra1028** [comment]
I said "Feel free to pull request" to about change the note of `setData` to a bold sentence, rather than to about adding a completion handler.

The UI extension is not the essence of DifferenceKit.
And, provide a helpfull interface for all cases is next to impossible.
I recommend you to create your own extesnsion in your code base.

**Comment by larryonoff** [comment]
updated documentation in #22

**Comment by ra1028** [comment]
@larryonoff 
Did you solve the a main subject of this issue?

**Comment by larryonoff** [comment]
Thanks. I'll close it. I'll check how the change works on Monday. I'm sure that it will.
