### ISSUE TITLE
Including DifferenceKit as a sub-project / SDKROOT issues

### ISSUE THREAD

**Issue by diederich** [ra1028/DifferenceKit#26]
Hey there,

first of all thanks for putting this online! 

I'm having issues integrating DiffereceKit via an Xcode sub-project (added via git submodule) in an iOS project, on Xcode 10 beta 6. 
I found that Xcode's not able to pick and set the right SDKROOT for DiffereceKit in command-line archive builds (same on Xcode server). So while the main project builds fine for iphoneos, once Xcode starts building DifferenceKit, it misses that and instead builds it with the macos SDK. (And then later fails linking).

I've put together a sample project: https://github.com/diederich/DifferenceKitArchive
This is how I can make the archive fail: 
`xcodebuild archive -project DifferenceKitArchive.xcodeproj -scheme DifferenceKitArchive`

I haven't tried this on Xcode 9 yet, neither with the old build system.
Have you seen anything like that?

**Comment by ra1028** [comment]
Hi @diederich 
I have not tried it with Xcode10 (because it's a beta release now).
Also, I haven't tried your project yet, but please try to use `-sdk` option.
as follows:
```
xcodebuild archive -project DifferenceKitArchive.xcodeproj -scheme DifferenceKitArchive -sdk iphoneos /* or iphonesimulator */
```

**Comment by diederich** [comment]
Hey @ra1028 - thanks for the quick reply!

I played a bit around setting build option, but I think specifying the sdk manually is not an option, as our scheme has various other targets (like watchOS extension, app, etc), and they won't build if we override the SDK for the whole scheme :-/

I'll try this with Xcode 9 (/old build system) and see if it that behaves differently...

**Comment by diederich** [comment]
Haven't tried with 9 yet, but I pushed the added the watch app to the demo project

**Comment by ra1028** [comment]
I close this issue.
If you still want to ask, please reopen it.
