### ISSUE TITLE
[Question] What is the proper way to load large amount of data from database

### ISSUE THREAD

**Issue by shuoli84** [ra1028/DifferenceKit#28]
Thanks for the awesome work :)

I have a large number of records in database (10w), and present them in an collection view. What is the proper way to utilize differencekit in this scenario.

My understandings:
* differencekit each compare takes O(n), so no matter how tiny the changes are, it still O(n).
* requires all dataset in memory.

**Comment by Sameesunkaria** [comment]
@shuoli84 If the diffing does not take that long (from the reference point of a user, approx. less than 500ms), you can perform the diffing on the background thread. Anything larger, DifferenceKit or any other diffing approach might not help you. Back to calling `performBatchUpdates`!

Also, if you don't want all the dataset in memory, again DifferenceKit might not be what you're looking for. Diffing requires that all the elements be compared and then a determination is reached of the outcome of the differences. Unless you have someway of performing comparisons (`==`) without hitting anything that is not in memory, you might be fine. The same goes for Hashes. If you are hitting the storage device or the network to fetch and compare the results, it'll be too slow to be of any advantage.

**Comment by Sameesunkaria** [comment]
@shuoli84 That should work. The comparisons can be made on the version number/identifier. And for the difference identifier, a primary key can also be stored in the section info.

Just to be clear, if the number of entries are too large, the diffing may still take enough time that it may cause a stutter if being computed on the main thread.

**Comment by ra1028** [comment]
@shuoli84 
Did you solve the problem?
Feel free to reopen this issue, if you didn't solved.
