### ISSUE TITLE
Can you add FlexibleDiff to your benchmarks and comparisons?

### ISSUE THREAD

**Issue by mluisbrown** [ra1028/DifferenceKit#3]
It seems surprising that you didn't add [FlexibleDiff](https://github.com/RACCommunity/FlexibleDiff) to your benchmarks and comparison tables. Would be good to have this, as it also uses the same algorithm.

**Comment by ra1028** [comment]
@mluisbrown 
OK!
I'll add FlexibleDiff to the README in next version.

**Comment by ra1028** [comment]
@mluisbrown 
[New version 0.3.0](https://github.com/ra1028/DifferenceKit/releases/tag/0.3.0) has released.
I added a comparison with FlexibleDiff to README.

**Comment by mluisbrown** [comment]
Thanks @ra1028 ! Wow that was an amazingly fast turnaround 👍 🎉
