### ISSUE TITLE
Using DifferenceKit in Objective-C project

### ISSUE THREAD

**Issue by Shebuka** [ra1028/DifferenceKit#37]
Hello,
Can this framework be used in an `Objective-C` project?

If yes, are there any examples of how to do this?
If no, what alternative can you suggest?

It seems to me that no. I've still tried but when I set my object to conform to protocol `Differentiable` Xcode can find it's declaration (I've imported the `xxx-Swift.h` in my object header).

**Comment by ra1028** [comment]
Hi @Shebuka

> Can this framework be used in an `Objective-C` project?

Nope.
And I have no plan to support objc.
Sorry.

**Comment by Sameesunkaria** [comment]
@Shebuka How about you add support for objc, on a fork, and if @ra1028 likes it, we all can have support for it in DeferenceKit. BTW, it shouldn't be that hard to do.

**Comment by Shebuka** [comment]
I've tried, but `Hashable` is not a valid `associatedtype` to be used with `objc`, and whole `Differentiable` needs to conform to `NSObjectProtocol` apparently. After searching around for a bit how to solve this I give up cause I'm not that expert in Swift...

**Comment by ra1028** [comment]
@Shebuka 
IGListKit has syntax similar to to DifferenceKit and it is fast enough.
I recommend using IGListKit.

**Comment by futuretap** [comment]
IGListKit doesn't work with watchOS.
