### ISSUE TITLE
Scrolling shutter since #40

### ISSUE THREAD

**Issue by crsantos** [ra1028/DifferenceKit#41]
Hey 👋 
First of all, awesome diff lib.

I started to detect some scrolling shutters when I updated to `0.7.2`.

Checking the commits, I see that #40 [introduced some `setContentOffset` calls](https://github.com/ra1028/DifferenceKit/pull/40/files#diff-ad0c1f1714695e2b18ec6951e2f8643aR117) and I think it may be related to that. 

I notice this when I scroll on my `UIColllectionView`
Sometimes, my scroll is canceled, probably due to a `setContentOffset` call when a reload is applied when I'm on the middle of a scroll event.

Did anyone notice this on `0.7.2`?

I can build sample app to demonstrate if needed.

**Comment by iCarambaa** [comment]
I also have a problem with the content offset setting. When deleting an item at the bottom of the collection view the collection view automatically updates the content offset which gets reverted by DifferenceKit. Imho, DifferenceKit should only perform the batch updates but not touch the content offset.

**Comment by crsantos** [comment]
I wasn't sure if you needed those `setContentOffset` lines, but if you don't, I can submit PR removing them

**Comment by ra1028** [comment]
This issue is fixed in https://github.com/ra1028/DifferenceKit/releases/tag/0.8.0.
Please reopen this issue if it recurs 👍
