### ISSUE TITLE
reload cell or header after move Transition ?

### ISSUE THREAD

**Issue by Wolly1985** [ra1028/DifferenceKit#44]
Hello i love Difference Kit and i have a question.

When i have changes in my datasource i call:

```
collectionView.reload(using: changeset) { (data) in
                self.data = data
            }
```

this works, but i need an update cell ,when i have a move transition from an element from section A to section B. In the section A all elements has cell.alpha = 1 and in sectionB all elements has cell.alpha = 0.5. (i use this in my example for a shopping list, section A has the items I still need and section B I already have :-))

No cellForItemAtIndexPath or willDisplayCell are calling in the UICollectionViewDataSource.

I hope someone can help me

Greetz

**Comment by ra1028** [comment]
Hi @Wolly1985,

`UICollectionView.moveItem` doesn't call `cellForItemAtIndexPath`.
If you want to update the cell appearance, you should return a `false` value in your model's `isContentEqual(to:)`.
This way DifferenceKit will call `reloadItem` and update cell appearances.

**Comment by Wolly1985** [comment]
Hi @ra1028 this reload all cells and not only this that moves. also the call reloadItem is before the item is move to the another section

greetz

**Comment by Wolly1985** [comment]
i found a Soulution with a edit CollectionView Extension. thx for help

`public extension UICollectionView {
    /// Applies multiple animated updates in stages using `StagedChangeset`.
    ///
    /// - Note: There are combination of changes that crash when applied simultaneously in `performBatchUpdates`.
    ///         Assumes that `StagedChangeset` has a minimum staged changesets to avoid it.
    ///         The data of the data-source needs to be updated synchronously before `performBatchUpdates` in every stages.
    ///
    /// - Parameters:
    ///   - stagedChangeset: A staged set of changes.
    ///   - interrupt: A closure that takes an changeset as its argument and returns `true` if the animated
    ///                updates should be stopped and performed reloadData. Default is nil.
    ///   - setData: A closure that takes the collection as a parameter.
    ///              The collection should be set to data-source of UICollectionView.
    
    func reload<C>(
        using stagedChangeset: StagedChangeset<C>,
        reloadChangeCells: Bool,
        interrupt: ((Changeset<C>) -> Bool)? = nil,
        setData: (C) -> Void
    ) {
        if case .none = window, let data = stagedChangeset.last?.data {
            setData(data)
            return reloadData()
        }
        
        let contentOffset = self.contentOffset
        var indexPaths: [IndexPath] = []
        for changeset in stagedChangeset {
            if let interrupt = interrupt, interrupt(changeset), let data = stagedChangeset.last?.data {
                setData(data)
                return reloadData()
            }
            
            performBatchUpdates({
                setData(changeset.data)
                
                if !changeset.sectionDeleted.isEmpty {
                    deleteSections(IndexSet(changeset.sectionDeleted))
                }
                
                if !changeset.sectionInserted.isEmpty {
                    insertSections(IndexSet(changeset.sectionInserted))
                }
                
                if !changeset.sectionUpdated.isEmpty {
                    reloadSections(IndexSet(changeset.sectionUpdated))
                }
                
                for (source, target) in changeset.sectionMoved {
                    moveSection(source, toSection: target)
                }
                
                if !changeset.elementDeleted.isEmpty {
                    deleteItems(at: changeset.elementDeleted.map { IndexPath(item: $0.element, section: $0.section) })
                }
                
                if !changeset.elementInserted.isEmpty {
                    insertItems(at: changeset.elementInserted.map { IndexPath(item: $0.element, section: $0.section) })
                }
                
                if !changeset.elementUpdated.isEmpty {
                    reloadItems(at: changeset.elementUpdated.map { IndexPath(item: $0.element, section: $0.section) })
                }
                
                for (source, target) in changeset.elementMoved {
                    moveItem(at: IndexPath(item: source.element, section: source.section), to: IndexPath(item: target.element, section: target.section))
                    indexPaths.append(IndexPath(item: target.element, section: target.section))
                }
            }) { (complete) in
                if reloadChangeCells {
                    self.reloadItems(at: indexPaths)
                }
            }
        }
        
        if contentSize.height > bounds.size.height {
            setContentOffset(contentOffset, animated: false)
        }
    }
}`

**Comment by Wolly1985** [comment]
my solution crashs after move many items has completion conflict with the datasource. but in performBatchUpdates its to early because when call moveItem, reloadItems(at: indexPaths) crashs because wrong index.

**Comment by ra1028** [comment]
@Wolly1985 
Sorry for my late reply.

I think you should contain all the rendering information in your model instance.
But you can workaround as below is also possible.

```swift
collectionView.reload(using: changeset) { data in
    self.data = data
}
collectionView.indexPathsForVisibleItems.forEach { indexPath in
    guard let cell = collectionView.cellForItem(at: indexPath) else { return }
    cell.alpha = indexPath.section == 0 ? 1 : 0.5
}
```

**Comment by ra1028** [comment]
I close this issue.
If you still want to ask, please reopen it.
