### ISSUE TITLE
pod search DifferenceKit and pod 'DifferenceKit/Core' Unable to find a pod

### ISSUE THREAD

**Issue by hqwsun** [ra1028/DifferenceKit#47]
I wanted to use "pod" method to install DifferenceKit, but I didn't find DifferenceKit. What's the matter, please。

Unable to find a pod with name, author, summary, or description matching `DifferenceKit`

**Comment by ra1028** [comment]
Duplicated https://github.com/ra1028/DifferenceKit/issues/48
