### ISSUE TITLE
Pod DifferenceKit not found

### ISSUE THREAD

**Issue by hqwsun** [ra1028/DifferenceKit#48]
pod 'DifferenceKit/Core'
Unable to find a specification for `DifferenceKit/Core`

pod search DifferenceKit
[!] Unable to find a pod with name, author, summary, or description matching `DifferenceKit`

**Comment by ra1028** [comment]
Hi @hqwsun ,
Sorry for my late reply.

Is your local CocoaPods repos up-to-date?
Please try following command:
`pod repo update`
 or
`pod install --repo-update`

If that doesn't work, please tell me your Podfile detail, CocoaPods version, Xcode version etc.

**Comment by ra1028** [comment]
I close this issue.
If you still want to ask, please reopen it.
