### ISSUE TITLE
Delete/Insert vs. Update

### ISSUE THREAD

**Issue by cnstoll** [ra1028/DifferenceKit#49]
Hi,

I love this library, but I'm having trouble figuring out the best practice for triggering an "update" to an existing element at a given location, versus having it be deleted and inserted. In my model, I'm just making a slight change to an element at a certain indexPath, and I'd like it to reload just that item instead of deleting the item and re-inserting it.

I'm assuming the problem is with my hashable or equatable implementation. Maybe I'm telling the library something wrong that's causing it to see an update as a delete/insert?

For a given item that implements Hashable and Equatable, how does DifferenceKit decide if an item is an updated version of the same element, or an entirely different element at the same location?

Thanks,

- Conrad

**Comment by ra1028** [comment]
I close this issue.
If you still want to ask, please reopen it.

**Comment by Streebor** [comment]
@ra1028 I have tried your solution and the updates are still not being triggered.
