### ISSUE TITLE
[BUG] An incorrect data array is generated for StagedChangeset

### ISSUE THREAD

**Issue by Sameesunkaria** [ra1028/DifferenceKit#5]
I have encountered a bug where an incorrect data array is generated when an element moves from an existing section to a new section. 

I have been able to modify one of the example projects to demonstrate this bug (Specifically the table view for the iOS example). Just tap the refresh button a couple of times to see the crash. 💥

Here's a link to the commit.
https://github.com/Sameesunkaria/DifferenceKit/commit/9582bff36135957220a3c95dbae2b7d94890ced5

Thanks for your efforts! 🍻

**Comment by ra1028** [comment]
@Sameesunkaria 
Thanks for quick reply!
OK, I'll release it now 👍

**Comment by ra1028** [comment]
@Sameesunkaria 
New version [0.4.0](New version released) released 🎉

**Comment by Sameesunkaria** [comment]
Already on it! Thanks a lot btw 🍻
