### ISSUE TITLE
Fix pod compilation in Xcode 10.2

### ISSUE THREAD

**Issue by gaetanzanella** [ra1028/DifferenceKit#56]
I created a blank swift 4.2 project with Xcode 10.2 & cocoapods 1.6.0 and I specified the following Podfile:

```
platform :ios, '11.0'

target 'Test' do
  use_frameworks!

  pod 'DifferenceKit', '~> 1.0'

end

```
The project does not compile. 

The DifferenceKit project compiles correctly on Xcode 10.2. So it seems to be only related to cocoapods.

**Comment by anlaital** [comment]
Should add `spec.swift_version = '4.2'` to `DifferenceKit.podspec`.

**Comment by BjornRuud** [comment]
Error with Swift 4.2 also. It seems the Swift 5 compiler doesn't like the Collection protocol conformance of StagedChangeset even in compatibility mode.

**Comment by gaetanzanella** [comment]
True but I also had to add:

```
extension StagedChangeset: RandomAccessCollection, RangeReplaceableCollection, MutableCollection {
    public typealias Element = Changeset<Collection>
```
in `StagedChangeset.swift`.

Looks like the swift compiler does not like the `Collection` generic type in `StagedChangeset`.

**Comment by BjornRuud** [comment]
I had to get this working right away in my fork, and created a pull request in case the repo owner wants it.
https://github.com/ra1028/DifferenceKit/pull/57

**Comment by MoElnaggar14** [comment]
I face the same problem

**Comment by Kaspik** [comment]
PR has been merged, I believe now @ra1028 just needs to do maybe some cosmetic changes in the project itself and then update version on CocoaPods etc.

**Comment by ra1028** [comment]
I'm now installing Xcode10.2 😂 
One moment, please.

**Comment by ra1028** [comment]
[Xcode10.2 compatible version](https://github.com/ra1028/DifferenceKit/releases/tag/1.1.0) has been released.
