### ISSUE TITLE
Upgrade supported Swift versions to include Swift 5

### ISSUE THREAD

**Issue by benasher44** [ra1028/DifferenceKit#64]
## Checklist
- [x] Reviewed the [README](https://github.com/ra1028/DifferenceKit/blob/master/README.md) and [documents](https://ra1028.github.io/DifferenceKit).  
- [x] Searched [existing issues](https://github.com/ra1028/DifferenceKit/issues) for ensure not duplicated.  

## Description
The podspec's swift_version supports providing multiple versions. It would be great to add Swift 5 or just upgrade to Swift 5-only altogether.

## Motivation and Context
Swift 5 is the latest stable version of Swift, and we're trying to get all of our pods building using Swift 5.

## Proposed Solution
`spec.swift_versions = ['4.2', '5.0']` or `spec.swift_version = '5.0'`

**Comment by ra1028** [comment]
Hi @benasher44 ,

OK, I'll add Swift 5 in the podspec next release.

**Comment by benasher44** [comment]
Thanks!

**Comment by ra1028** [comment]
@benasher44 
I just published DifferenceKit v1.1.2 https://github.com/ra1028/DifferenceKit/releases/tag/1.1.2 including Swift 5 support in podspec.

**Comment by benasher44** [comment]
Works great! Thanks!
