### ISSUE TITLE
Completion handler after reload

### ISSUE THREAD

**Issue by rajeshnitt73** [ra1028/DifferenceKit#7]
Could be better if there is an completion handler after reload.

**Comment by ra1028** [comment]
Hi @rajeshnitt73 
You can handle the completion after animated reload with `CATransaction` as follows.
```swift
CATransaction.begin()
CATransaction.setCompletionBlock {
    // handle completion
}
tableView.reload(using: changeset, with: .fade) { data in
    dataSource.data = data
}
CATransaction.commit()
```

However, if implement it on DifferenceKit, it may makes worse versatility or causes bug in edge cases.
I recommend to implement it on your project.
If there are a lot of requests, I'll consider to  implement it on DifferenceKit 👍

**Comment by rajeshnitt73** [comment]
Ok that makes sense. Thank you for your great efforts.

**Comment by ekazaev** [comment]
TBH, I also have a request for the completion block.
