### ISSUE TITLE
ArraySection compile error: Type 'C' constrained to non-protocol, non-class type `[Element]`

### ISSUE THREAD

**Issue by cnstoll** [ra1028/DifferenceKit#72]
Great. This template thing completely removed what I wrote.

**Comment by cnstoll** [comment]
Since I can't really re-write all of that, basically I'm getting the error in the title trying to compile ArraySection in Xcode 10.2.1.

<img width="1162" alt="Screen Shot 2019-05-29 at 7 04 24 PM" src="https://user-images.githubusercontent.com/1586401/58607267-8e76c680-8264-11e9-829c-1d4c961f8760.png">

For some reason that I can't explain, changing Collection to Sequence fixes it. 🤷‍♂ 

<img width="877" alt="Screen Shot 2019-05-29 at 10 22 31 PM" src="https://user-images.githubusercontent.com/1586401/58607309-bc5c0b00-8264-11e9-9224-039c2b96e469.png">

I think this is related to a recent update that added the Element associated type, but I'm honestly not sure.

**Comment by cnstoll** [comment]
It looks like this is a namespacing issue. The compiler thinks that "Collection" is the DifferenceKit's Collection instead of the Swift.Collection version. Changing "Collection" to "Swift.Collection" also fixes this error.

**Comment by ra1028** [comment]
Hi @cnstoll ,

Thanks for your reporting.
I can compile without problems in my environment.
Let me know more about your situation according to issue template you deleted?
https://github.com/ra1028/DifferenceKit/blob/master/.github/ISSUE_TEMPLATE/QUESTION.md

**Comment by larsacus** [comment]
I can confirm this is a result of the namespace aliasing between `Swift.Collection` and the "re-defined" associated type `Collection: Swift.Collection where Collection.Element: Differentiable` in `DifferentiableSection.swift`. Same workaround as above "fixes" the issue, but there may be some other lingering issues with having this associated type named the same as a system type.

Xcode 10.2, Swift 4.2

**Comment by AnisovAleksey** [comment]
The same issue. Reproduced only in Archive, debug build works fine.

Xcode: 12.5
Cocoapods: 1.10.1
Library version: 1.2.0
