### ISSUE TITLE
Build Libraries For Distribution (Swift compatibility)

### ISSUE THREAD

**Issue by andrewconlan** [ra1028/DifferenceKit#86]
Enabling Build Libraries For Distribution flag to YES in the project's build settings causes errors, not sure of the best approach to fix?

<img width="1140" alt="Screenshot 2019-11-06 at 16 12 26" src="https://user-images.githubusercontent.com/1355096/68316067-b6d6dc80-00b0-11ea-8476-a62fd28a4d36.png">

**Comment by ra1028** [comment]
@andrewconlan 
Thanks for reporting!
That's due to redundant defining `@inlinable` attributes.
I'm trying to enable library evolution mode in [here](https://github.com/ra1028/DifferenceKit/pull/88).

**Comment by andrewconlan** [comment]
Thanks for looking at this, updated and it looks good, will close my issue. The project is fantastic by the way 🥳
