### ISSUE TITLE
AppKitExtension wrong usage of changeset

### ISSUE THREAD

**Issue by martindufort** [ra1028/DifferenceKit#90]
## Expected Behavior
The following code at line 80,81 of <AppKitExtension.swift> is referencing **elementInserted** where it should be **elementUpdated**

```swift
   if !changeset.elementUpdated.isEmpty {
                reloadData(forRowIndexes: IndexSet(changeset.elementInserted.map { $0.element }), columnIndexes: IndexSet(changeset.elementInserted.map { $0.section }))
            } 
```

**Comment by ra1028** [comment]
Hi, @martindufort 
Thanks for your reporting!
Sorry, this is an obvious bug that has been hidden for a long time.
I'll make a patch release right away.
